version: '3.9'

services:
  postgres:
    image: postgres:16-alpine
    container_name: chat_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: chatapp
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d chatapp"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: chat_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: chat_backend
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      PORT: 8080
      DB_URL: postgres://admin:admin@postgres:5432/chatapp?sslmode=disable
      REDIS_URL: redis://redis:6379
      JWT_SECRET: 6bb01df2bd4e7bbbe33cde0c7d9c5a83076f78bc42787256709d5dc2805d15fc
      JWT_REFRESH_SECRET: e0f4cd0561a4b1b22ef14fbf250aa2c5397d6c4fb3cf21ce4f3e0578112bbb8e
      UPLOAD_DIR: /app/uploads
      TZ: Asia/Ho_Chi_Minh
    ports:
      - "8080:8080"
    volumes:
      - uploads_data:/app/uploads

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: chat_frontend
    restart: unless-stopped
    depends_on:
      - backend
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:8080/api
      NEXT_PUBLIC_WS_URL: ws://localhost:8080/ws
      TZ: Asia/Ho_Chi_Minh
    ports:
      - "3000:3000"

volumes:
  postgres_data:
  redis_data:
  uploads_data:
